### PR TITLE
Fix infinite loops in mono

### LINKED ISSUE #675: Bug: infinite loop in `--monomorphize`
Compiling the following code with `charon rustc --monomorphize --extract-opaque-bodies` loop infinitely:
```rust
#![feature(btree_extract_if)]
use std::collections::BTreeSet;
use std::mem;

#[derive(PartialEq, Eq, PartialOrd, Ord)]
pub enum Foo {
    A(&'static str),
    _B,
    _C,
}

pub fn main() {
    let mut b = BTreeSet::new();
    b.insert(Foo::A("\'"));
}
```

### PR DESCRIPTION
**Pull request by N1ark**
Fixes #675 -- was caused by monomorphization detecting types in `PathElem::Impl`s as uses of that type

### CODE REVIEW

File: charon/tests/ui/monomorphization/rec-adt.rs [hunk 1]
```diff
@@ -0,0 +1,21 @@
+use std::marker::PhantomData;
```
Comment (Nadrieril) [inline charon/tests/ui/monomorphization/rec-adt.rs:2]:
```suggestion
//@ charon-args=--monomorphize
use std::marker::PhantomData;
```

File: charon/tests/ui/monomorphization/rec-adt.out [hunk 2]
```diff
@@ -0,0 +1,38 @@
+# Final LLBC before serialization:
+
+// Full name: core::marker::Sized
+#[lang_item("sized")]
+pub trait Sized<Self>
+
+pub struct test_crate::LinkedList::<u8> {
+  head: core::option::Option::<NonNull<Node<u8>[Sized<u8>]>>,
```
Comment (Nadrieril) [inline charon/tests/ui/monomorphization/rec-adt.out:8]: How come the output doesn't include that type?

Comment (N1ark) [reply charon/tests/ui/monomorphization/rec-adt.out:8]: oh that is.. a good question????

Comment (N1ark) [reply charon/tests/ui/monomorphization/rec-adt.out:8]: wait i think it's because of short names??? because the type decl is in the .llbc file so ??

Comment (Nadrieril) [reply charon/tests/ui/monomorphization/rec-adt.out:8]: Short names should not change anything, they're only used for pretty-printing

Comment (Nadrieril) [reply charon/tests/ui/monomorphization/rec-adt.out:8]: I do see the item in the llbc file :thinking: :thinking: tha'ts weird

Comment (N1ark) [reply charon/tests/ui/monomorphization/rec-adt.out:8]: no ideak actually - the llbc file has all the right information, i dont know why its skipped at printing

Comment (Nadrieril) [reply charon/tests/ui/monomorphization/rec-adt.out:8]: Oh it's because of `ordered_decls`. We use that as a basis for printing items, but it's missing `TypeDeclId(6)` for some reason

Comment (Nadrieril) [reply charon/tests/ui/monomorphization/rec-adt.out:8]: Let's fix that separately
